### PR TITLE
Support RcArray

### LINKED ISSUE #4: Support RcArray
This will be possible without cloning Array.

### PR DESCRIPTION
**Pull request by termoshtt**
Resolve #4 

TODO
-------
- [x] impl traits for RcArray
  - [x] impl Vector for RcArray
  - [x] impl Matrix for RcArray
  - [x] impl SquareMatrix for RcArray
  - [x] impl TrianglarMatrix for RcArray
  - [x] impl HermiteMatrix for RcArray
- [x] Tests
  - [x] all_close_l2 for any array #25
  - [x] Generate test for RcArray using macro
  - [x] replace to_owned -> into_owned (as possible)

### CODE REVIEW

**Comment by termoshtt** [comment]
We need `into_owned(self) -> Array` to reduce copies.

**Comment by bluss** [comment]
`RcArray::into_owned() -> Array` sounds fine to me. Note that it will need to use the usual clone on write logic (if the rcarray is shared).

**Comment by bluss** [comment]
I don't see a way to avoid the cloning of elements in any of the `&self` methods. If `self` is `&RcArray`, then the array's data is by necessity shared (there exists at least one Rc handle that is not consumed then).

**Comment by termoshtt** [comment]
Yes, `to_owned()` cannot be replaced by `into_owned()` for `&self` method as you say.
I should consider to get `&[f64]` from `RcArray` directory.

Anyway, there are already many unnecessary clones in this crate. I will remove them incrementally.

**Comment by termoshtt** [comment]
Completeness of tests depends on my attentiveness. I'd like to use coverage tools :<
https://users.rust-lang.org/t/tutorial-how-to-collect-test-coverages-for-rust-project/650

**Comment by bluss** [comment]
into_owned has been added upstream (not released yet)

**Comment by termoshtt** [comment]
Thanks, I saw [the PR](https://github.com/bluss/rust-ndarray/pull/266). I will include it in this PR.

**Pull request merged**
